esphome:
  name: lsc-plug-1

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

wifi:
  ap:
    ssid: "LSC-Plug Hotspot"
    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

# LED2 on board
status_led:
  pin: P26

output:
  # LED1 on board
  - platform: gpio
    id: relay_1_led
    pin: P8
    
binary_sensor:
  # SW1 on board
  - platform: gpio
    id: button_1
    name: lsc-plug-1_button
    pin:
      number: P7
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    on_press:
      - switch.toggle: relay_1

switch:
  # RY1 on board
  - platform: gpio
    id: relay_1
    name: lsc-plug-1_relay
    pin: P6
    on_turn_on:
      - output.turn_on: relay_1_led
    on_turn_off:
      - output.turn_off: relay_1_led
