esphome:
  name: ctrl-one
  name_add_mac_suffix: true
  friendly_name: CTRL ONE
  min_version: 2026.7.0

esp32:
  variant: esp32c6

logger:

spi:
  clk_pin: GPIO19
  mosi_pin: GPIO18

i2c:
  sda: GPIO3
  scl: GPIO2
  scan: false
  frequency: 100kHz

sensor:
  - platform: adc
    pin: GPIO6
    name: Ambient Light
    id: ambient_light
    update_interval: 3s
    attenuation: auto
    unit_of_measurement: lx
    device_class: illuminance
    filters:
      - lambda: |-
          if (id(backlight).current_values.is_on()) {
            return {};  // suppress reading when backlight is on
          }
          // ALS-PT19 behind 1.5mm aperture, 3.3V, 10KΩ to GND
          // Rough calibration for indoor use
          return x * 4000.0f;
  - platform: scd4x
    id: scd40
    co2:
      name: "CO2"
      id: scd_co2_raw
      filters:
        - skip_initial: 3
    temperature:
      name: "Temperature"
      id: scd_temperature_raw
      filters:
        - skip_initial: 4
        - lambda: |-
            if (id(indicator_light).current_values.is_on()) {
              return {};  // suppress reading when indicator is on
            }
            return x;
    humidity:
      name: "Humidity"
      id: scd_humidity_raw
    automatic_self_calibration: false
    measurement_mode: low_power_periodic
    update_interval: 30s

output:
  - platform: ledc
    id: screen_led
    frequency: 1220Hz
    min_power: 0.05
    zero_means_zero: true
    pin:
      number: GPIO7
  - platform: ledc
    id: rgb_r
    frequency: 1220Hz
    pin:
      number: GPIO8
      inverted: true
  - platform: ledc
    id: rgb_b
    frequency: 1220Hz
    pin:
      number: GPIO14
      inverted: true
  - platform: ledc
    id: rgb_g
    frequency: 1220Hz
    pin:
      number: GPIO15
      inverted: true

light:
  - platform: monochromatic
    output: screen_led
    id: backlight
    name: "Screen Light"
    restore_mode: ALWAYS_OFF
  - platform: rgb
    id: indicator_light
    name: Indicator Light
    red: rgb_r
    green: rgb_g
    blue: rgb_b

display:
  - platform: epaper_spi
    id: goodisplay
    model: goodisplay-gdey042t81-4.2
    cs_pin: GPIO20
    dc_pin: GPIO21
    busy_pin: GPIO23
    reset_pin: GPIO22
    update_interval: never
    full_update_every: 5
    auto_clear_enabled: false

touchscreen:
  - platform: ft63x6
    id: touch_digitizer
    interrupt_pin: GPIO4
    reset_pin: GPIO5
