# Board: T1-U Wi-Fi Module
# Definition: definitions/boards/t1-u/manifest.yaml

esphome:
  name: lsc-smart-connect-floor-lamp
  friendly_name: LSC Smart Connect Smart Floor Lamp


bk72xx:
  board: generic-bk7238-tuya

logger:

wifi:
  ap:

light:
  - platform: beken_spi_led_strip
    name: Main
    pin: P16
    id: light_beken_spi_led_strip_1
    chipset: SM16703
    num_leds: 96
    rgb_order: GRB
    effects:
      - addressable_rainbow:
      - addressable_twinkle:
  - platform: rgbw
    name: Base
    blue: blue_base
    green: green_base
    red: red_base
    white: white_base
    id: light_rgbw_1
    icon: "mdi:lightbulb"
    restore_mode: ALWAYS_ON

output:
  - platform: libretiny_pwm
    pin: P9
    id: blue_base
  - platform: libretiny_pwm
    pin: P24
    id: green_base
  - platform: libretiny_pwm
    pin: P8
    id: red_base
  - platform: libretiny_pwm
    pin: P26
    id: white_base


remote_receiver:
  id: ir_rx
  pin:
    number: P23
    inverted: true
    mode:
      input: true
      pullup: true

binary_sensor:
  - platform: gpio
    name: Touch Button
    pin:
      number: P22
      mode:
        input: true
        pullup: true
      inverted: true
    id: binary_sensor_gpio_1
    on_click:
      - then:
          - light.toggle: light_beken_spi_led_strip_1
