i2c:
  sda: GPIO18
  scl: GPIO19

sensor:
  # 4. Temperature & Humidity
  - platform: aht10
    variant: AHT20
    address: 0x38
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 30s
