# Hardware configuration for Minco Heat MK80W
packages:
  base: !include base.yaml

uart:
  id: tuya_uart
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600
  rx_buffer_size: 1024

time:
  - platform: sntp
    id: ntp_time
    timezone: "Europe/Moscow"
    
tuya:
  id: tuya_bus
  uart_id: tuya_uart
  time_id: ntp_time 

switch:
  - platform: gpio
    pin: GPIO7
    id: thermo_status_pin
    restore_mode: ALWAYS_OFF

  - platform: tuya
    name: "Thermostat Child Lock"
    switch_datapoint: 40

  - platform: tuya
    name: "Thermostat Anti-Frost Mode"
    switch_datapoint: 103

climate:
  - platform: tuya
    id: thermostat_climate
    name: "Thermostat"
    switch_datapoint: 1
    target_temperature_datapoint: 16
    current_temperature_datapoint: 101
    temperature_multiplier: 0.1

select:
  - platform: tuya
    name: "Thermostat Backlight Mode"
    enum_datapoint: 52
    options:
      0: "Turn Off after 15s"
      1: "Dim after 15s"

  - platform: tuya
    name: "Thermostat Sensor Source"
    enum_datapoint: 43
    options:
      0: "Internal Air Sensor (IN)"
      1: "External Floor Sensor (OUT)"
      2: "Dual Combined Sensor (ALL)"
