esphome:
  name: button
  friendly_name: button
  on_boot:
    - priority: 550
      then:
        - light.turn_on:
            id: white_light
            effect: "Connecting"
    - priority: 225.0
      then:
        - output.turn_on: cap_charge
        - http_request.get:
            url: http://url.to.my.http/api/
            on_response:
              then:
                - if:
                    condition:
                      lambda: "return status_code == 200;"
                    then:
                      - light.turn_off:
                          id: white_light
                      - light.turn_on:
                          id: green_light
                      - delay: 2s
                      - deep_sleep.enter:
                          id: deep_sleep_forever
                    else:
                      - light.turn_off:
                          id: white_light
                      - light.turn_on:
                          id: red_light
                          effect: "Error"
                      - delay: 2s
                      - deep_sleep.enter:
                          id: deep_sleep_forever

deep_sleep:
  id: deep_sleep_forever
  run_duration: 20s #This is ignored when the deep_sleep.enter is called above
  # not setting a sleep duration means sleep forever

http_request:
  useragent: esphome/device
  timeout: 10s

esp8266:
  board: esp_wroom_02

# Enable logging
logger:

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: pwm_white
    inverted: true
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm_green
    inverted: true
  - platform: esp8266_pwm
    pin: GPIO14
    id: pwm_red
    inverted: true
  - platform: gpio
    id: cap_charge
    pin: GPIO4

light:
  - platform: monochromatic
    id: white_light
    output: pwm_white
    name: "White LED"
    effects:
      - pulse:
          name: "Connecting"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 10%
          max_brightness: 60%
  - platform: monochromatic
    id: green_light
    output: pwm_green
    name: "Green LED"
  - platform: monochromatic
    id: red_light
    output: pwm_red
    name: "Red LED"
    effects:
      - pulse:
          name: "Error"
          transition_length: 0.2s
          update_interval: 0.2s
          min_brightness: 0%
          max_brightness: 100%
