esphome:
  name: upk2esphome-bk7231t
bk72xx:
  board: generic-bk7231t-qfn32-tuya

logger:

wifi:
  ap:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P11
      inverted: false
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P26
    on_turn_on:
      - light.turn_off: relay_status_led  # Invert LED state
    on_turn_off:
      - light.turn_on: relay_status_led   # Invert LED state

output:
  - platform: gpio
    pin: P6
    id: relay_status_led_output

light:
  - platform: binary
    output: relay_status_led_output
    id: relay_status_led
